version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: 172.31.32.100 #this is host of HAProxy Server
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  wordpress2:
    image: wordpress
    restart: always
    ports:
      - 81:80
    environment:
      WORDPRESS_DB_HOST: 172.31.32.100 #this is host of HAProxy Server
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html


volumes:
  wordpress:
